# Generated by Django 4.0.1 on 2022-01-31 20:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Страховка')),
                ('description', models.TextField(verbose_name='опис')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Посада')),
                ('calary', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Зарплата')),
                ('description', models.TextField(verbose_name='опис')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='опис')),
            ],
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Iмя')),
                ('patronymic', models.CharField(max_length=120, verbose_name='По-батьковi')),
                ('surname', models.CharField(max_length=120, verbose_name='Прiзвище')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('email', models.CharField(max_length=120, verbose_name='Електронна скринька')),
                ('description', models.TextField(verbose_name='опис')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.insurance', verbose_name='Страховка')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.post', verbose_name='Посада')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.status', verbose_name='Статус')),
            ],
        ),
    ]
