# Generated by Django 4.0.1 on 2022-02-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_employers_options_alter_insurance_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employers',
            new_name='Employer',
        ),
    ]
